### ISSUE TITLE
关于登录的问题

### ISSUE THREAD

**Issue by Meteor8** [ligb888/huya-danmu#1]
非常好用！
但是登录看不太明白
sendClient传入的nickname是什么？cookie该怎么填？
谢谢大佬

**Comment by ligb888** [comment]
> 非常好用！
> 但是登录看不太明白
> sendClient传入的nickname是什么？cookies该怎么填？
> 谢谢大佬

nickname就传账号昵称，随便传也可以，只是做个标记。
cookies你看test代码里的那个格式，把网页里面所有的cookies转成这种格式就行了
一般用python获取的cookies默认就是这个格式

**Comment by Meteor8** [comment]
> cookies你看test代码里的那个格式，把网页里面所有的cookies转成这种格式就行了

好像`client.js`里面的cookie字典循环是不是有些错误...
我把`_cookie_convert()`和`_get_cookie_value(name)`里面的字典循环改成`for(let key in this.cookies)`就可以登陆了...

**Comment by igofreely** [comment]
大佬，可以提供一个cookie的例子吗（[{"domain": ".huya.com", "httpOnly": false, "name": "huya_web_rep_cnt", "path": "/", "secure": false, "value": "361"}]），在哪个页面抓的cookie，websocket页面好像没有cookie

**Comment by Meteor8** [comment]
登录以后直接在控制台输入`document.cookie`就会返回cookie，然后转一下格式
以下是改了cookie字典后的格式，要使用的话记得把字典循环改成`for(let key in this.cookies)`
```
{
    "vplayer_sbanner_1199538205888_1199538205888":"1",
    "vplayer_sbanner_0_0":"1",
    "guid":"",
    "__yamid_new":"",
    "__yamid_tt1":"",
    "udb_guiddata":"",
    "videoLine":"",
    "_ga":"",
    "alphaValue":"",
    "SoundValue":"0.90",
    "isInLiveRoom":"true",
    "udb_accdata":"",
    "avatar":"",
    "nickname":"",
    "partner_uid":"",
    "udb_openid":"",
    "udb_origin":"",
    "udb_other":"",
    "udb_passport":"",
    "udb_status":"1",
    "udb_uid":"",
    "udb_version":"1.0",
    "username":"",
    "yyuid":"",
    "udb_biztoken":"",
    "videoBitRate":"2000",
    "h_unt":"",
    "__yasmid":"",
    "__yaoldyyuid":"",
    "_yasids":"",
    "udb_passdata":"3",
    "huya_hd_rep_cnt":"5",
    "huya_flash_rep_cnt":"24",
    "huya_web_rep_cnt":"30"
};
```

**Comment by ligb888** [comment]
> 大佬，可以提供一个cookie的例子吗（[{"domain": ".huya.com", "httpOnly": false, "name": "huya_web_rep_cnt", "path": "/", "secure": false, "value": "361"}]），在哪个页面抓的cookie，websocket页面好像没有cookie

test里面就有例子，格式不一样话可以手动转换一下。或者像他们一样把cookie的遍历改掉

**Comment by ligb888** [comment]
> 登录以后直接在控制台输入`document.cookie`就会返回cookie，然后转一下格式
> 以下是改了cookie字典后的格式，要使用的话记得把字典循环改成`for(let key in this.cookies)`
> 
> ```
> {
>     "vplayer_sbanner_1199538205888_1199538205888":"1",
>     "vplayer_sbanner_0_0":"1",
>     "guid":"",
>     "__yamid_new":"",
>     "__yamid_tt1":"",
>     "udb_guiddata":"",
>     "videoLine":"",
>     "_ga":"",
>     "alphaValue":"",
>     "SoundValue":"0.90",
>     "isInLiveRoom":"true",
>     "udb_accdata":"",
>     "avatar":"",
>     "nickname":"",
>     "partner_uid":"",
>     "udb_openid":"",
>     "udb_origin":"",
>     "udb_other":"",
>     "udb_passport":"",
>     "udb_status":"1",
>     "udb_uid":"",
>     "udb_version":"1.0",
>     "username":"",
>     "yyuid":"",
>     "udb_biztoken":"",
>     "videoBitRate":"2000",
>     "h_unt":"",
>     "__yasmid":"",
>     "__yaoldyyuid":"",
>     "_yasids":"",
>     "udb_passdata":"3",
>     "huya_hd_rep_cnt":"5",
>     "huya_flash_rep_cnt":"24",
>     "huya_web_rep_cnt":"30"
> };
> ```

之前用的都是python抓的，跟网页上不一样，你们可以自行发挥哈

**Comment by igofreely** [comment]
> > 登录以后直接在控制台输入`document.cookie`就会返回cookie，然后转一下格式
> > 以下是改了cookie字典后的格式，要使用的话记得把字典循环改成`for(let key in this.cookies)`
> > ```
> > {
> >     "vplayer_sbanner_1199538205888_1199538205888":"1",
> >     "vplayer_sbanner_0_0":"1",
> >     "guid":"",
> >     "__yamid_new":"",
> >     "__yamid_tt1":"",
> >     "udb_guiddata":"",
> >     "videoLine":"",
> >     "_ga":"",
> >     "alphaValue":"",
> >     "SoundValue":"0.90",
> >     "isInLiveRoom":"true",
> >     "udb_accdata":"",
> >     "avatar":"",
> >     "nickname":"",
> >     "partner_uid":"",
> >     "udb_openid":"",
> >     "udb_origin":"",
> >     "udb_other":"",
> >     "udb_passport":"",
> >     "udb_status":"1",
> >     "udb_uid":"",
> >     "udb_version":"1.0",
> >     "username":"",
> >     "yyuid":"",
> >     "udb_biztoken":"",
> >     "videoBitRate":"2000",
> >     "h_unt":"",
> >     "__yasmid":"",
> >     "__yaoldyyuid":"",
> >     "_yasids":"",
> >     "udb_passdata":"3",
> >     "huya_hd_rep_cnt":"5",
> >     "huya_flash_rep_cnt":"24",
> >     "huya_web_rep_cnt":"30"
> > };
> > ```
> 
> 之前用的都是python抓的，跟网页上不一样，你们可以自行发挥哈

感谢大佬回复，python怎么抓的，登陆有验证码是不是接打码平台或者手动输入验证码，是不是用的selenium？

**Comment by igofreely** [comment]
知道怎么抓cookie了
from selenium import webdriver
from selenium.webdriver.support.wait import WebDriverWait

web_driver=webdriver.Chrome()
web_driver.get('https://www.huya.com/357831')
WebDriverWait(web_driver,30,0.2).until(lambda x:x.find_element_by_xpath("/html/body/div[1]/div/div/div[3]/div/div[6]/div/div/div/a/span"))
cookie=web_driver.get_cookies()
print(cookie)

**Comment by ligb888** [comment]
> > > 登录以后直接在控制台输入`document.cookie`就会返回cookie，然后转一下格式
> > > 以下是改了cookie字典后的格式，要使用的话记得把字典循环改成`for(let key in this.cookies)`
> > > ```
> > > {
> > >     "vplayer_sbanner_1199538205888_1199538205888":"1",
> > >     "vplayer_sbanner_0_0":"1",
> > >     "guid":"",
> > >     "__yamid_new":"",
> > >     "__yamid_tt1":"",
> > >     "udb_guiddata":"",
> > >     "videoLine":"",
> > >     "_ga":"",
> > >     "alphaValue":"",
> > >     "SoundValue":"0.90",
> > >     "isInLiveRoom":"true",
> > >     "udb_accdata":"",
> > >     "avatar":"",
> > >     "nickname":"",
> > >     "partner_uid":"",
> > >     "udb_openid":"",
> > >     "udb_origin":"",
> > >     "udb_other":"",
> > >     "udb_passport":"",
> > >     "udb_status":"1",
> > >     "udb_uid":"",
> > >     "udb_version":"1.0",
> > >     "username":"",
> > >     "yyuid":"",
> > >     "udb_biztoken":"",
> > >     "videoBitRate":"2000",
> > >     "h_unt":"",
> > >     "__yasmid":"",
> > >     "__yaoldyyuid":"",
> > >     "_yasids":"",
> > >     "udb_passdata":"3",
> > >     "huya_hd_rep_cnt":"5",
> > >     "huya_flash_rep_cnt":"24",
> > >     "huya_web_rep_cnt":"30"
> > > };
> > > ```
> > 
> > 之前用的都是python抓的，跟网页上不一样，你们可以自行发挥哈
> 
> 感谢大佬回复，python怎么抓的，登陆有验证码是不是接打码平台或者手动输入验证码，是不是用的selenium？

是selenium哈，全自动肯定要打码平台哈，很多cookie还是用python好抓一些，不然可能会在支付上有问题
