### ISSUE TITLE
你好，我最近在做关于虎牙弹幕机器人，请问有没有完整的虎牙弹幕数据格式文档

### ISSUE THREAD

**Issue by br3ant** [ligb888/huya-danmu#2]

**Comment by ligb888** [comment]
这个抓一抓数据看一看吧，这个代码里面做了一些封装，把主要的数据提取出来了。你可以看看

**Comment by br3ant** [comment]
用websoket抓出来的全是二进制数据，怎么去解析呢

**Comment by ligb888** [comment]
> 用websoket抓出来的全是二进制数据，怎么去解析呢

所以要这代码干嘛的呢。。。不就包括解析吗，源码都给了。。

**Comment by br3ant** [comment]
普通用户解析好了，但是房管在房间里发言，返回的req是{'iVersion': 3, 'cPacketType': 0, 'iMessageType': 0, 'iRequestId': 0, 'sServantName': 'liveui', 'sFuncName': 'sendMessage', 'sBuffer': b'\x08\x00\x01\x06\x00\x1d\x00\x00\x02\x00\xff', 'iTimeout': 0, 'context': {}, 'status': {'STATUS_RESULT_DESC': 'require field not exist, tag: 0 headType: 1, headTag: 1', 'STATUS_SETNAME_VALUE': 'huya.sz.32'}}，房管还需要发送什么特殊的内容吗

**Comment by ligb888** [comment]
> 普通用户解析好了，但是房管在房间里发言，返回的req是{'iVersion': 3, 'cPacketType': 0, 'iMessageType': 0, 'iRequestId': 0, 'sServantName': 'liveui', 'sFuncName': 'sendMessage', 'sBuffer': b'\x08\x00\x01\x06\x00\x1d\x00\x00\x02\x00\xff', 'iTimeout': 0, 'context': {}, 'status': {'STATUS_RESULT_DESC': 'require field not exist, tag: 0 headType: 1, headTag: 1', 'STATUS_SETNAME_VALUE': 'huya.sz.32'}}，房管还需要发送什么特殊的内容吗

能打印出返回就能打印出请求哦，可以用房管用户去网页上操作，然后把包复制代码里解析出来，就能分析为什么了

**Comment by br3ant** [comment]
打开虎牙直播有大量的wss连接，找不到到wss://cdnws.api.huya.com ，你知道是那个websocket连接吗
